$(document).ready(function() {
  $('input.munic').autocomplete({
    data: {
      "AC": "Acre",
      "Alvaraes": null,
      "Amatura": null,
      "Anama": null,
      "Anori": null,
      "Apui": null,
      "Atalaia do Norte": null,
      "Autazes": null,
      "Barcelos": null,
      "Barreirinha": null,
      "Benjamin Constant": null,
      "Beruri": null,
      "Boa Vista do Ramos": null,
      "Boca do Acre": null,
      "Borba": null,
      "Caapiranga": null,
      "Canutama": null,
      "Carauari": null,
      "Careiro da Varzea": null,
      "Careiro": null,
      "Coari": null,
      "Codajas": null,
      "Eirunepe": null,
      "Envira": null,
      "Fonte Boa": null,
      "Guajara": null,
      "Humaita": null,
      "Ipixuna": null,
      "Iranduba": null,
      "Itacoatiara": null,
      "Itamarati": null,
      "Itapiranga": null,
      "Japura": null,
      "Jurua": null,
      "Jutai": null,
      "Labrea": null,
      "Manacapuru": null,
      "Manaquiri": null,
      "Manaus": null,
      "Manicore": null,
      "Maraa": null,
      "Maues": null,
      "Nhamunda": null,
      "Nova Olinda do Norte": null,
      "Novo Airao": null,
      "Novo Aripuana": null,
      "Parintins": null,
      "Pauini": null,
      "Presidente Figueiredo": null,
      "Rio Preto da Eva": null,
      "Santa Isabel do Rio Negro": null,
      "Santo Antonio do Ica": null,
      "Sao Gabriel da Cachoeira": null,
      "Sao Paulo de Olivenca": null,
      "Sao Sebastiao do Uatuma": null,
      "Silves": null,
      "Tabatinga": null,
      "Tapaua": null,
      "Tefe": null,
      "Tonantins": null,
      "Uarini": null,
      "Urucara": null,
      "Urucurituba": null
    },
  });
});