$(document).ready(function() {
  $('input.autocomplete').autocomplete({
    data: {
      "Afeganistão": null,
      "África do Sul": null,
      "Akrotiri": null,
      "Albânia": null,
      "Alemanha": null,
      "Andorra": null,
      "Angola": null,
      "Anguila": null,
      "Antárctida": null,
      "Antígua e Barbuda": null,
      "Arábia Saudita": null,
      "Arctic Ocean": null,
      "Argélia": null,
      "Argentina": null,
      "Arménia": null,
      "Aruba": null,
      "Ashmore and Cartier Islands": null,
      "Atlantic Ocean": null,
      "Austrália": null,
      "Áustria": null,
      "Azerbaijão": null,
      "Baamas": null,
      "Bangladeche": null,
      "Barbados": null,
      "Barém": null,
      "Bélgica": null,
      "Belize": null,
      "Benim": null,
      "Bermudas": null,
      "Bielorrússia": null,
      "Birmânia": null,
      "Bolívia": null,
      "Bósnia e Herzegovina": null,
      "Botsuana": null,
      "Brasil": null,
      "Brunei": null,
      "Bulgária": null,
      "Burquina Faso": null,
      "Burúndi": null,
      "Butão": null,
      "Cabo Verde": null,
      "Camarões": null,
      "Camboja": null,
      "Canadá": null,
      "Catar": null,
      "Cazaquistão": null,
      "Chade": null,
      "Chile": null,
      "China": null,
      "Chipre": null,
      "Clipperton Island": null,
      "Colômbia": null,
      "Comores": null,
      "Congo-Brazzaville": null,
      "Congo-Kinshasa": null,
      "Coral Sea Islands": null,
      "Coreia do Norte": null,
      "Coreia do Sul": null,
      "Costa do Marfim": null,
      "Costa Rica": null,
      "Croácia": null,
      "Cuba": null,
      "Curacao": null,
      "Dhekelia": null,
      "Dinamarca": null,
      "Domínica": null,
      "Egipto": null,
      "Emiratos Árabes Unidos": null,
      "Equador": null,
      "Eritreia": null,
      "Eslováquia": null,
      "Eslovénia": null,
      "Espanha": null,
      "Estados Unidos": null,
      "Estónia": null,
      "Etiópia": null,
      "Faroé": null,
      "Fiji": null,
      "Filipinas": null,
      "Finlândia": null,
      "França": null,
      "Gabão": null,
      "Gâmbia": null,
      "Gana": null,
      "Gaza Strip": null,
      "Geórgia": null,
      "Geórgia do Sul e Sandwich do Sul": null,
      "Gibraltar": null,
      "Granada": null,
      "Grécia": null,
      "Gronelândia": null,
      "Guame": null,
      "Guatemala": null,
      "Guernsey": null,
      "Guiana": null,
      "Guiné": null,
      "Guiné Equatorial": null,
      "Guiné-Bissau": null,
      "Haiti": null,
      "Honduras": null,
      "Hong Kong": null,
      "Hungria": null,
      "Iémen": null,
      "Ilha Bouvet": null,
      "Ilha do Natal": null,
      "Ilha Norfolk": null,
      "Ilhas Caimão": null,
      "Ilhas Cook": null,
      "Ilhas dos Cocos": null,
      "Ilhas Falkland": null,
      "Ilhas Heard e McDonald": null,
      "Ilhas Marshall": null,
      "Ilhas Salomão": null,
      "Ilhas Turcas e Caicos": null,
      "Ilhas Virgens Americanas": null,
      "Ilhas Virgens Britânicas": null,
      "Índia": null,
      "Indian Ocean": null,
      "Indonésia": null,
      "Irão": null,
      "Iraque": null,
      "Irlanda": null,
      "Islândia": null,
      "Israel": null,
      "Itália": null,
      "Jamaica": null,
      "Jan Mayen": null,
      "Japão": null,
      "Jersey": null,
      "Jibuti": null,
      "Jordânia": null,
      "Kosovo": null,
      "Kuwait": null,
      "Laos": null,
      "Lesoto": null,
      "Letónia": null,
      "Líbano": null,
      "Libéria": null,
      "Líbia": null,
      "Listenstaine": null,
      "Lituânia": null,
      "Luxemburgo": null,
      "Macau": null,
      "Macedónia": null,
      "Madagáscar": null,
      "Malásia": null,
      "Malávi": null,
      "Maldivas": null,
      "Mali": null,
      "Malta": null,
      "Man, Isle of": null,
      "Marianas do Norte": null,
      "Marrocos": null,
      "Maurícia": null,
      "Mauritânia": null,
      "México": null,
      "Micronésia": null,
      "Moçambique": null,
      "Moldávia": null,
      "Mónaco": null,
      "Mongólia": null,
      "Monserrate": null,
      "Montenegro": null,
      "Mundo": null,
      "Namíbia": null,
      "Nauru": null,
      "Navassa Island": null,
      "Nepal": null,
      "Nicarágua": null,
      "Níger": null,
      "Nigéria": null,
      "Niue": null,
      "Noruega": null,
      "Nova Caledónia": null,
      "Nova Zelândia": null,
      "Omã": null,
      "Pacific Ocean": null,
      "Países Baixos": null,
      "Palau": null,
      "Panamá": null,
      "Papua-Nova Guiné": null,
      "Paquistão": null,
      "Paracel Islands": null,
      "Paraguai": null,
      "Peru": null,
      "Pitcairn": null,
      "Polinésia Francesa": null,
      "Polónia": null,
      "Porto Rico": null,
      "Portugal": null,
      "Quénia": null,
      "Quirguizistão": null,
      "Quiribáti": null,
      "Reino Unido": null,
      "República Centro-Africana": null,
      "República Dominicana": null,
      "Roménia": null,
      "Ruanda": null,
      "Rússia": null,
      "Salvador": null,
      "Samoa": null,
      "Samoa Americana": null,
      "Santa Helena": null,
      "Santa Lúcia": null,
      "São Bartolomeu": null,
      "São Cristóvão e Neves": null,
      "São Marinho": null,
      "São Martinho": null,
      "São Pedro e Miquelon": null,
      "São Tomé e Príncipe": null,
      "São Vicente e Granadinas": null,
      "Sara Ocidental": null,
      "Seicheles": null,
      "Senegal": null,
      "Serra Leoa": null,
      "Sérvia": null,
      "Singapura": null,
      "Sint Maarten": null,
      "Síria": null,
      "Somália": null,
      "Southern Ocean": null,
      "Spratly Islands": null,
      "Sri Lanca": null,
      "Suazilândia": null,
      "Sudão": null,
      "Sudão do Sul": null,
      "Suécia": null,
      "Suíça": null,
      "Suriname": null,
      "Svalbard e Jan Mayen": null,
      "Tailândia": null,
      "Taiwan": null,
      "Tajiquistão": null,
      "Tanzânia": null,
      "Território Britânico do Oceano Índico": null,
      "Territórios Austrais Franceses": null,
      "Timor Leste": null,
      "Togo": null,
      "Tokelau": null,
      "Tonga": null,
      "Trindade e Tobago": null,
      "Tunísia": null,
      "Turquemenistão": null,
      "Turquia": null,
      "Tuvalu": null,
      "Ucrânia": null,
      "Uganda": null,
      "União Europeia": null,
      "Uruguai": null,
      "Usbequistão": null,
      "Vanuatu": null,
      "Vaticano": null,
      "Venezuela": null,
      "Vietname": null,
      "Wake Island": null,
      "Wallis e Futuna": null,
      "West Bank": null,
      "Zâmbia": null,
      "Zimbabué": null
    },
  });
});